// worker-configuration.d.ts (generated by `wrangler types`) marks every
// binding optional, since it can't know which bindings a given `--env`
// selection guarantees. We only ever deploy with the default environment's
// full binding set, so this narrows them back to required for app code.
declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
    MEDIA: R2Bucket;
    // Local-dev/test-only: set via .dev.vars, never a real deployed secret
    // (see docs/security.md and src/middleware.ts).
    E2E_BYPASS_SECRET?: string;
  }
}

declare namespace App {
  interface Locals {
    /** Verified Access JWT email claim — set only on /admin and /api/admin routes. */
    accessEmail?: string;
  }
}
